# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a Python image with UV installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS uv

# Set the working directory
WORKDIR /app

# Copy the project files to the container
COPY . .

# Use UV to install the dependencies from the lock file
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev --no-editable

# Install the project itself
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-editable

# Use a minimal Python image for the final release
FROM python:3.12-slim-bookworm

# Set the working directory
WORKDIR /app

# Copy installed dependencies and the virtual environment from the UV stage
COPY --from=uv /root/.local /root/.local
COPY --from=uv --chown=app:app /app/.venv /app/.venv

# Ensure executables are available on PATH
ENV PATH="/app/.venv/bin:$PATH"

# Set the entrypoint for the Docker container
ENTRYPOINT ["docker-mcp"]
